### ISSUE TITLE
Introduction to golang

### ISSUE THREAD

**Issue by mfrw** [IIIT-Delhi/Byld-Sessions#1]
I am planning to have an introductory-intermediate session on `golang`.
What say?

**Comment by geekSiddharth** [comment]
@mfrw  It would be awesome! What day suits you?

**Comment by mfrw** [comment]
@geekSiddharth What about next week?
Any suggestion regarding content are welcome.

**Comment by geekSiddharth** [comment]
@mfrw Can you please upload the contents?
